baseURL = 'https://ahzed11.github.io/guide-oz/'
languageCode = 'fr-be'
title = 'Guide OZ'
# enableGitInfo = true

[params]
BookTheme = 'auto'
description = 'Guide collaboratif pour OZ'
# images = ['site-feature-image.jpg']
title = 'Guide OZ'
prism_css = ["css/prism.css"]
prism_js = ["js/prism.js"]
